services:
  - type: web
    name: bookstore-server
    env: node
    buildCommand: cd server && npm install
    startCommand: node server/index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: bookstore-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    buildFilter:
      paths:
        - client/**